// Code generated by mockery v2.32.4. DO NOT EDIT.

package fake

import (
	context "context"

	worker "github.com/nduyphuong/gorya/internal/worker"
	mock "github.com/stretchr/testify/mock"
)

// Interface is an autogenerated mock type for the Interface type
type Interface struct {
	mock.Mock
}

// Dispatch provides a mock function with given fields: ctx, e
func (_m *Interface) Dispatch(ctx context.Context, e *worker.QueueElem) error {
	ret := _m.Called(ctx, e)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *worker.QueueElem) error); ok {
		r0 = rf(ctx, e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Process provides a mock function with given fields: ctx, resultChan, errChan
func (_m *Interface) Process(ctx context.Context, resultChan chan<- string, errChan chan<- error) {
	_m.Called(ctx, resultChan, errChan)
}

// NewInterface creates a new instance of Interface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *Interface {
	mock := &Interface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
